version: 0.2
phases:
  pre_build:
    commands:
      - echo "🚀 Installing dependencies..."
      - ls
      - npm install
    build:
      commands:
      - echo "🚀 Building remix application..."
      - npm run build
cache:
  paths:
    - node_modules/**/*
artifacts:
  files:
    - '**/*'